apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodapi-metrics
  labels:
    app: foodapi-metrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodapi-metrics
  template:
    metadata:
      labels:
        app: foodapi-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: foodapi
        image: nginx:alpine
        ports:
        - containerPort: 8080
        command: ["/bin/sh", "-c"]
        args:
        - |
          cat > /etc/nginx/conf.d/default.conf << 'EOF'
          server {
              listen 8080;
              server_name localhost;
              location / {
                  return 200 '{"status": "Food API Running", "version": "1.0.0"}';
                  add_header Content-Type application/json;
              }
              location /health {
                  return 200 '{"status": "ok", "service": "foodapi"}';
                  add_header Content-Type application/json;
              }
              location /metrics {
                  return 200 '# HELP foodapi_orders_created_total Total orders created
          # TYPE foodapi_orders_created_total counter
          foodapi_orders_created_total 42
          
          # HELP foodapi_order_duration_seconds Order processing duration
          # TYPE foodapi_order_duration_seconds histogram
          foodapi_order_duration_seconds_bucket{le="0.01"} 5
          foodapi_order_duration_seconds_bucket{le="0.05"} 25
          foodapi_order_duration_seconds_bucket{le="0.1"} 35
          foodapi_order_duration_seconds_bucket{le="0.5"} 42
          foodapi_order_duration_seconds_bucket{le="+Inf"} 42
          foodapi_order_duration_seconds_sum 8.2
          foodapi_order_duration_seconds_count 42
          
          # HELP foodapi_active_users Current active users
          # TYPE foodapi_active_users gauge
          foodapi_active_users 15
          
          # HELP foodapi_crops_monitored Total crops monitored
          # TYPE foodapi_crops_monitored gauge
          foodapi_crops_monitored 156';
                  add_header Content-Type text/plain;
              }
          }
          EOF
          nginx -g 'daemon off;'
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: foodapi-metrics
  labels:
    app: foodapi-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: foodapi-metrics
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foodapi-metrics
  labels:
    app: foodapi-metrics
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: foodapi-metrics
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s